version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: illuminate/pipeline
    versions:
    - 8.29.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.39.0
  - dependency-name: laravel-zero/foundation
    versions:
    - 8.29.0
    - 8.29.1
    - 8.32.1
    - 8.34.0
    - 8.35.1
    - 8.37.0
  - dependency-name: illuminate/filesystem
    versions:
    - 8.29.0
    - 8.30.0
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
  - dependency-name: composer/composer
    versions:
    - 1.10.20
    - 1.10.21
  - dependency-name: filp/whoops
    versions:
    - 2.11.0
    - 2.9.2
  - dependency-name: symfony/mime
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: illuminate/testing
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
  - dependency-name: illuminate/cache
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/contracts
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/config
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/console
    versions:
    - 8.24.0
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/collections
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/bus
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/macroable
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/container
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
  - dependency-name: illuminate/support
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
